spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shp_test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=round&tinyInt1isBit=false&useSSL=false
    username: postgres
    password: jskj@2020
    driver-class-name: org.postgresql.Driver
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/big_event
#    username: root
#    password: jskj@2020
#  data:
#    redis:
#      host: 47.108.155.60
#      port: 6379
#      password: yt@1372049

debug: false

#mybatis
mybatis-plus:
  mapper-locations: classpath*:cn/giseryung/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#    lazy-loading-enabled: false
#    multiple-result-sets-enabled: true
#    use-column-label: true
#    use-generated-keys: true
#    default-executor-type: simple
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.xiaominfo.knife4j.demo.web
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn