spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:postgresql://localhost:5432/shp_test?currentSchema=public&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=round&tinyInt1isBit=false&useSSL=false&stringtype=unspecified
    username: postgres
    password: jskj@2020
    #    password: yt123456
    driver-class-name: org.postgresql.Driver
    # 数据库连接池配置（HikariCP）
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 50
      minimumIdle: 5
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/big_event
#    username: root
#    password: jskj@2020
#  data:
#    redis:
#      host: 47.108.155.60
#      port: 6379
#      password: yt@1372049

debug: false

#mybatis
mybatis-plus:
  mapper-locations: classpath*:cn/giseryung/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
#    lazy-loading-enabled: false
#    multiple-result-sets-enabled: true
#    use-column-label: true
#    use-generated-keys: true
#    default-executor-type: simple
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
    enabled: true
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.xiaominfo.knife4j.demo.web
  packages-to-scan: cn.giseryung.mybatisstudy.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
  basic:
    username: yt
    password: 123

# 分页
pagehelper:
  #  propertyName: propertyValue
  reasonable: true # 启用合理化，如果pageNum<1会查询第一页，如果pageNum>pages会查询最后一页
  defaultCount: true # 分页插件默认参数支持 default-count 形式，自定义扩展的参数，必须大小写一致
#  page-size-zero: true  # pageSize=0 查询出全部的结果
